config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :songs
  
  get 'home/about'
  root 'home#index'

  get 'export_songs', to: 'songs#report', as: 'song_report'
  get 'export_authors', to: 'authors#report', as: 'author_report'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_and_belongs_to_many :songs

    has_many :comments, as: :commentable, dependent: :destroy
    accepts_nested_attributes_for :comments, allow_destroy: true

    has_one_attached :profile_image

    def complete_name
        "#{name} #{surname}"
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true
end

app/models/song.rb
class Song < ApplicationRecord
    has_and_belongs_to_many :authors
    accepts_nested_attributes_for :authors

    has_many :comments, as: :commentable, dependent: :destroy
    accepts_nested_attributes_for :comments, allow_destroy: true

    has_one_attached :image_cover
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    require 'rubyXL/convenience_methods'
    
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    @author.comments.new
  end

  # GET /authors/1/edit
  def edit
  end

  # DOWNLOAD Excel Report
  def report
    path = "/Users/gpozzobon/Desktop/authors.xlsx"
    authors = Author.all
    workbook = RubyXL::Workbook.new
    worksheet = workbook[0]

    #HEADERS
    worksheet.add_cell(0, 0, "ID")
    worksheet.add_cell(0, 1, "Name")
    worksheet.add_cell(0, 2, "Surname")

    worksheet.add_cell(0, 4, "created_at")
    worksheet.add_cell(0, 5, "updated_at")

    #BODY
    (0..authors.count-1).to_a.each{ |row|
      
      worksheet.add_cell(row+1, 0, authors[row].id)
      worksheet.add_cell(row+1, 1, authors[row].name)
      worksheet.add_cell(row+1, 2, authors[row].surname)

      worksheet.add_cell(row+1, 4, authors[row].created_at.to_s)
      worksheet.add_cell(row+1, 5, authors[row].updated_at.to_s)
    }

    workbook.write(path)
    send_file(path)
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: 'Author was successfully updated.'}
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed."}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :surname, :profile_image, comments_attributes: [:author, :message])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @song.comments.new
    @song.authors.new
  end

  # GET /songs/1/edit
  def edit
  end

  # DOWNLOAD Excel Report
  def report
    path = "/Users/gpozzobon/Desktop/songs.xlsx"
    songs = Song.all
    authors = Author.all
    workbook = RubyXL::Workbook.new
    worksheet = workbook[0]

    #HEADERS
    worksheet.add_cell(0, 0, "ID")
    worksheet.add_cell(0, 1, "Title")
    worksheet.add_cell(0, 2, "Authors")
    worksheet.add_cell(0, 3, "Album")
    worksheet.add_cell(0, 4, "Plays")
    worksheet.add_cell(0, 5, "Notes")

    worksheet.add_cell(0, 7, "created_at")
    worksheet.add_cell(0, 8, "updated_at")

    #BODY
    (0..songs.count-1).to_a.each{ |row|
      
      worksheet.add_cell(row+1, 0, songs[row].id)
      worksheet.add_cell(row+1, 1, songs[row].title)
      worksheet.add_cell(row+1, 2, songs[row].authors.map{|a| "#{a.name} #{a.surname}" }.join(", ")) unless songs[row].authors.nil?
      worksheet.add_cell(row+1, 3, songs[row].album)
      worksheet.add_cell(row+1, 4, songs[row].plays)
      worksheet.add_cell(row+1, 5, songs[row].comments.map{|a| "#{a.message}" }.join(".\r\n")) unless songs[row].comments.nil?

      worksheet.add_cell(row+1, 7, songs[row].created_at.to_s)
      worksheet.add_cell(row+1, 8, songs[row].updated_at.to_s)
    }

    workbook.write(path)
    send_file(path)
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :album, :plays, :image_cover, comments_attributes: [:song, :message], author_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/authors/_form.html.haml
= simple_form_for @author do |f|
  = f.input :name
  = f.input :surname
  - if author.profile_image.attached?
    = image_tag(author.profile_image, style: 'height:200px;width:auto;', class: 'mb-3')
  - else
    = f.input :profile_image, input_html: { accept: ('image/png, image/gif, image/jpeg') }
  = f.simple_fields_for :comments do |comments_form|
    = comments_form.input :message
  %br
  = f.button :submit, "Save", class: "btn btn-primary"

app/views/authors/edit.html.haml
%h1.mt-3.mb-3 Editing Author: 

= render 'form', author: @author

= link_to 'Back', authors_path, class:"mt-3 btn btn-secondary"

app/views/authors/index.html.haml
%p#notice= notice

%h1 Authors

%table.table.table-dark.table-striped
  %thead
    %tr
      %th
      %th Name
      %th Surname
      %th{:colspan => "3"}
      
  %tbody
    - @authors.each do |author|
      %tr
        %td
          - if author.profile_image.attached?
            = image_tag(author.profile_image, style: 'height:30px;')

        %td= author.name
        %td= author.surname
        %td= link_to icon('fa-solid', 'eye'), author
        %td= link_to icon('fa-solid', 'file-pen'), edit_author_path(author)
        %td= link_to icon('fa-solid', 'trash'), author, method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'Download Report', author_report_path, class:"btn btn-primary mr-3"

= link_to 'New Author', new_author_path, class:"btn btn-secondary"

app/views/authors/new.html.haml
%h1.mt-3.mb-3 New Author: 

= render 'form', author: @author

= link_to 'Back', authors_path, class:"mt-3 btn btn-secondary"

app/views/authors/show.html.haml
%p#notice= notice

.card
  .card-header Details
  .card-body
    - if @author.profile_image.attached?
      = image_tag @author.profile_image, class:"card-img-top mb-5", style: 'height:200px;width:auto;', alt: "Profile Image"
    - else
      %p.small No profile pic.
    %h5.card-title= "#{@author.name} #{@author.surname}"
    %p.card-text In my opinion, a very magnificent author. Let's see what people think:

    %section{:style => "background-color: #eee;"}
      .container.py-5.h-100
        .row.d-flex.align-items-center.h-100

          - if @author.comments.count == 0
            %p.small.ml-5= "Nothing to say, great author."
          - else
            .col.col-lg-6.mb-4.mb-lg-0
              %figure.bg-white.p-3.rounded{:style => "border-left: .25rem solid #a34e78;"}
                - @author.comments.map do |c| 
                  %blockquote.blockquote.pb-2= c.message
              %figcaption.blockquote-footer.mb-0.font-italic Anonymous
    %br
    %br
    = link_to 'Back', authors_path, class:"btn btn-secondary"

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <%= link_to 'MyApp', root_path, class:'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to 'About Me', home_about_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
            <%= link_to 'Songs', songs_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
            <%= link_to 'Authors', authors_path, class:'nav-link' %>
        </li>

      </ul>
    </div>
  
  </div>
</nav>

app/views/home/about.html.haml
%h1{:class => "mt-3 mb-3"} About me

%p Hi, my name is Giacomo. I created this App as a test. Bye

app/views/home/index.html.haml
%h1{:class => "mt-3 mb-3"} Welcome Page
%p created by Giacomo @20 Sep 2022

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>MyApp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'home/footer' %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/songs/_form.html.haml
= simple_form_for @song do |f|
  = f.input :title
  = f.association :authors, :collection => Author.all, :as => :check_boxes, label_method: :complete_name, value_method: :id, :include_hidden => false
  - if song.image_cover.attached?
    = image_tag(song.image_cover, style: 'height:200px;width:auto;', class: 'mb-3')
  - else
    = f.input :image_cover, input_html: { accept: ('image/png, image/gif, image/jpeg') }
  = f.input :album
  = f.input :plays
  = f.simple_fields_for :comments do |comments_form|
    = comments_form.input :message
  = f.button :submit, "Save", class: "btn btn-primary"

app/views/songs/edit.html.haml
%h1{:class => "mt-3 mb-3"} Edit datas: 

= render 'form', song: @song

= link_to 'Back', songs_path, class:"mt-3 btn btn-secondary"

app/views/songs/index.html.haml
%p#notice= notice

%h1 Songs

%table.table.table-dark.table-striped
  %thead
    %tr
      %th
      %th Title
      %th Author
      %th Album
      %th{:colspan => "3"}

  %tbody
    - @songs.each do |song|
      %tr
        %td
          - if song.image_cover.attached?
            = image_tag(song.image_cover, style: 'height:30px;')
        %td= song.title
        %td= song.authors.map{|author| "#{author.name} #{author.surname}"}.join(", ")
        %td= song.album
        %td= link_to icon('fa-solid', 'eye'), song
        %td= link_to icon('fa-solid', 'file-pen'), edit_song_path(song)
        %td= link_to icon('fa-solid', 'trash'), song, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'Download Report', song_report_path, class:"btn btn-primary mr-3"

= link_to 'New Song', new_song_path, class:"btn btn-secondary"

app/views/songs/new.html.haml
%h1{:class => "mt-3 mb-3"} Insert a new song: 

= render 'form', song: @song

= link_to 'Back', songs_path, class:"mt-3 btn btn-secondary"

app/views/songs/show.html.haml
%p#notice= notice

.card
  .card-header Details
  .card-body
    - if @song.image_cover.attached?
      = link_to image_tag(@song.image_cover, class:"card-img-top mb-5", style: 'height:200px;width:auto;', alt: "Cover Image"), @song.image_cover, download: ''
    - else
      %p.small No image cover.

    %h5.card-title= @song.title
    %p.card-text
      A song by 
      %b= "#{@song.authors.map{ |author| author.name + ' ' + author.surname }.join(", ")}"
      , included in the album 
      %b= "#{@song.album}"
      
      %p.card-text
        %b= "#{@song.plays} plays."
        on
        %b Spotify
        %br
      %p.card-text Let's see what people think:
      %section{:style => "background-color: #eee;"}
        .container.py-5.h-100
          .row.d-flex.align-items-center.h-100

            - if @song.comments.count == 0
              %p.small.ml-5= "Nothing to say, great song."
            - else
              .col.col-lg-6.mb-lg-0
                %figure.bg-white.p-3.rounded{:style => "border-left: .25rem solid #a34e78;"}
                  - @song.comments.map do |c| 
                    %blockquote.blockquote.pb-2= c.message
                %figcaption.blockquote-footer.mb-0.font-italic Anonymous
      %br

    = link_to 'Back', songs_path, class:"btn btn-secondary"